# Generated by Django 5.2.4 on 2025-07-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('public_date', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
            ],
        ),
    ]
